# Generated by Django 4.2.3 on 2023-07-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='prediction1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='prediction2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='voting',
            field=models.FloatField(default=0),
        ),
    ]
