# Generated by Django 4.2.3 on 2023-07-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stockinfo_prediction1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACCStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('correct', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='prediction1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='prediction2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='voting',
            field=models.FloatField(),
        ),
    ]
