# Generated by Django 4.2.3 on 2023-07-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_accstocks_alter_stockinfo_prediction1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accstocks',
            name='rmse',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
