# Generated by Django 4.2.3 on 2023-07-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stockstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstype',
            name='stock_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
