# Generated by Django 4.2.3 on 2023-07-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stockstype_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accstocks',
            name='high_correct',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accstocks',
            name='high_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
