# Generated by Django 4.2.3 on 2023-07-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_stockshistory_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockshistory',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
