# Generated by Django 4.2.3 on 2023-07-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_alter_stockshistory_current_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accstocks',
            old_name='correct',
            new_name='all',
        ),
        migrations.RenameField(
            model_name='accstocks',
            old_name='count',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='accstocks',
            old_name='high_correct',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='accstocks',
            old_name='high_count',
            new_name='pred_high',
        ),
        migrations.AddField(
            model_name='accstocks',
            name='pred_high_correct',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accstocks',
            name='pred_low',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accstocks',
            name='pred_low_correct',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
