# Generated by Django 4.2.3 on 2023-07-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_rename_correct_accstocks_all_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accstocks',
            old_name='all',
            new_name='count',
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='price',
            field=models.FloatField(),
        ),
    ]
