# Generated by Django 4.2.3 on 2023-07-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_file_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockshistory',
            name='range',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockshistory',
            name='target',
            field=models.DecimalField(decimal_places=2, default=321, max_digits=10),
            preserve_default=False,
        ),
    ]
