# Generated by Django 4.2.3 on 2023-07-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_stockshistory_range_stockshistory_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stock_id', models.CharField(max_length=50)),
                ('prediction1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prediction2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pred1_future', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pred2_future', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='voting',
        ),
        migrations.AddField(
            model_name='accstocks',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accstocks',
            name='pwp',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accstocks',
            name='wp',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='pred1_future',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='pred2_future',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='accstocks',
            name='rmse',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='prediction1',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='prediction2',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
