# Generated by Django 4.2.3 on 2023-07-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_typesinfo_remove_stockinfo_voting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
