# Generated by Django 4.2.3 on 2023-07-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_alter_typesinfo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accstocks',
            name='stock_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='stock_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
