# Generated by Django 4.2.3 on 2023-07-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_alter_accstocks_stock_id_alter_stockinfo_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockinfo',
            constraint=models.UniqueConstraint(fields=('date', 'stock_id'), name='unique_stock_per_date'),
        ),
    ]
