# Generated by Django 4.2.3 on 2023-07-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0021_stockshistory_model_name_stockshistory_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockshistory',
            name='wp',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
